# Generated by Django 4.2.13 on 2026-06-07 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='楼层名称')),
                ('code', models.CharField(max_length=50, verbose_name='楼层编码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'floor',
                'ordering': ['project', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100, unique=True, verbose_name='批次号')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='供应商')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总数量')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已入库数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='单价')),
                ('status', models.CharField(choices=[('pending', '待入库'), ('in_stock', '已入库'), ('partial', '部分入库')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'material_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='类别名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类别编码')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='material_management.materialcategory', verbose_name='父级类别')),
            ],
            options={
                'db_table': 'material_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='项目地址')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分区名称')),
                ('code', models.CharField(max_length=50, verbose_name='分区编码')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='material_management.zone', verbose_name='父级分区')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='material_management.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['project', 'level', 'sort_order'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('operator', '操作员'), ('auditor', '审核员')], default='operator', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='小组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_groups', to=settings.AUTH_USER_MODEL, verbose_name='组长')),
                ('members', models.ManyToManyField(blank=True, related_name='responsibility_groups', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='material_management.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'responsibility_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_no', models.CharField(max_length=100, unique=True, verbose_name='领用单号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='领用数量')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='用途说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('used', '已领用')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_usages', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usages', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='material_management.floor', verbose_name='使用楼层')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='material_management.materialbatch', verbose_name='材料批次')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='material_management.materialcategory', verbose_name='材料类别')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='material_management.project', verbose_name='所属项目')),
                ('responsibility_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='material_management.responsibilitygroup', verbose_name='责任小组')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_usages', to=settings.AUTH_USER_MODEL, verbose_name='领用人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='material_management.zone', verbose_name='领用分区')),
            ],
            options={
                'db_table': 'material_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=100, unique=True, verbose_name='转移单号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='转移数量')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_transfers', to='material_management.floor', verbose_name='源楼层')),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transfers', to='material_management.zone', verbose_name='源分区')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='material_management.materialbatch', verbose_name='材料批次')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='material_management.materialcategory', verbose_name='材料类别')),
                ('to_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_transfers', to='material_management.floor', verbose_name='目标楼层')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transfers', to='material_management.zone', verbose_name='目标分区')),
            ],
            options={
                'db_table': 'material_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='material_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='material_management.materialcategory', verbose_name='材料类别'),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='material_management.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='floor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='material_management.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_no', models.CharField(max_length=100, unique=True, verbose_name='异常编号')),
                ('exception_type', models.CharField(choices=[('shortage', '库存不足'), ('damage', '材料损坏'), ('quality', '质量问题'), ('overage', '数量过剩'), ('other', '其他异常')], max_length=50, verbose_name='异常类型')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='涉及数量')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('handling_suggestion', models.TextField(blank=True, null=True, verbose_name='处理建议')),
                ('handling_result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='material_management.floor', verbose_name='楼层位置')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('material_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='material_management.materialbatch', verbose_name='材料批次')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='material_management.materialcategory', verbose_name='材料类别')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='material_management.project', verbose_name='所属项目')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='material_management.zone', verbose_name='所属分区')),
            ],
            options={
                'db_table': 'exception_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='material_management.floor', verbose_name='楼层位置')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='material_management.materialbatch', verbose_name='所属批次')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='material_management.materialcategory', verbose_name='材料类别')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='material_management.zone', verbose_name='所属分区')),
            ],
            options={
                'db_table': 'material_stock',
                'ordering': ['-updated_at'],
                'unique_together': {('zone', 'material_category', 'material_batch', 'floor')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('project', 'code')},
        ),
    ]
