# Generated by Django 4.2.13 on 2026-06-07 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_no', models.CharField(max_length=100, unique=True, verbose_name='盘点单号')),
                ('check_range', models.TextField(blank=True, null=True, verbose_name='盘点范围说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待审核'), ('approved', '审核通过'), ('rejected', '审核拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('handling_opinion', models.TextField(blank=True, null=True, verbose_name='处理意见')),
                ('audit_opinion', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('check_date', models.DateField(verbose_name='盘点日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='复盘人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_checks', to='material_management.floor', verbose_name='盘点楼层')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_checks', to='material_management.project', verbose_name='所属项目')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_checks', to='material_management.zone', verbose_name='盘点分区')),
            ],
            options={
                'db_table': 'inventory_check',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='账面数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='实盘数量')),
                ('diff_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='差异数量')),
                ('diff_type', models.CharField(choices=[('no_diff', '无差异'), ('overage', '盘盈'), ('shortage', '盘亏')], default='no_diff', max_length=20, verbose_name='差异类型')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='material_management.inventorycheck', verbose_name='关联盘点单')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_check_items', to='material_management.materialbatch', verbose_name='材料批次')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_check_items', to='material_management.materialcategory', verbose_name='材料类别')),
            ],
            options={
                'db_table': 'inventory_check_item',
                'ordering': ['id'],
            },
        ),
    ]
