# Generated by Django 4.2.13 on 2026-06-07 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material_management', '0002_inventorycheck_inventorycheckitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbatch',
            name='inbound_date',
            field=models.DateField(blank=True, null=True, verbose_name='入库日期'),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='safety_threshold',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15, verbose_name='安全库存阈值'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='shelf_life_days',
            field=models.IntegerField(default=180, verbose_name='保质期(天)'),
        ),
        migrations.CreateModel(
            name='MaterialWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_no', models.CharField(max_length=100, unique=True, verbose_name='预警编号')),
                ('warning_type', models.CharField(choices=[('low_stock', '低库存预警'), ('expiring', '临期预警'), ('long_unused', '长期未使用预警'), ('overstock', '库存积压预警')], max_length=50, verbose_name='预警类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('description', models.TextField(verbose_name='预警描述')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='当前数量')),
                ('threshold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='阈值数量')),
                ('warning_days', models.IntegerField(default=0, verbose_name='预警天数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('processed', '已处理'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('handling_opinion', models.TextField(blank=True, null=True, verbose_name='处理意见')),
                ('handling_result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warnings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='material_management.floor', verbose_name='楼层位置')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_warnings', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('material_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='material_management.materialbatch', verbose_name='材料批次')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='material_management.materialcategory', verbose_name='材料类别')),
                ('material_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='material_management.materialstock', verbose_name='关联库存')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='material_management.project', verbose_name='所属项目')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_warnings', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='material_management.zone', verbose_name='所属分区')),
            ],
            options={
                'db_table': 'material_warning',
                'ordering': ['-created_at'],
            },
        ),
    ]
