# Generated by Django 4.2.13 on 2026-06-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0003_materialbatch_inbound_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialwarning',
            name='force_close',
            field=models.BooleanField(default=False, verbose_name='是否强制关闭'),
        ),
        migrations.AddField(
            model_name='materialwarning',
            name='related_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='material_management.exceptionrecord', verbose_name='关联异常单'),
        ),
        migrations.AddField(
            model_name='materialwarning',
            name='related_inventory_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='material_management.inventorycheck', verbose_name='关联盘点单'),
        ),
        migrations.AddField(
            model_name='materialwarning',
            name='related_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='material_management.materialusage', verbose_name='关联领用单'),
        ),
    ]
