# Generated by Django 4.2.13 on 2026-06-07 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material_management', '0004_materialwarning_force_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建预警'), ('assign', '指派责任人'), ('start_process', '开始处理'), ('update_opinion', '更新处理意见'), ('relate_usage', '关联领用单'), ('relate_exception', '关联异常单'), ('relate_inventory', '关联盘点单'), ('auto_close', '自动闭环'), ('auto_reopen', '自动恢复待处理'), ('process', '标记已处理'), ('force_close', '强制关闭'), ('ignore', '忽略'), ('reopen', '重新打开')], max_length=50, verbose_name='操作类型')),
                ('action_detail', models.TextField(blank=True, null=True, verbose_name='操作详情')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='变更前状态')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='变更后状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('related_exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.exceptionrecord', verbose_name='关联异常单')),
                ('related_inventory_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.inventorycheck', verbose_name='关联盘点单')),
                ('related_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_management.materialusage', verbose_name='关联领用单')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='material_management.materialwarning', verbose_name='关联预警')),
            ],
            options={
                'db_table': 'warning_process_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
